### ISSUE TITLE
add machine readable content that says how you wish this to be cited

### ISSUE THREAD

**Issue by egonw** [bergmanlab/drosophila-transposons#31]
E.g. with a citation.CFF file, see https://citation-file-format.github.io/1.0.3/specifications/

**Comment by cbergman** [comment]
Great suggestion. I'll add this in the next sprint. Thanks!

**Comment by cbergman** [comment]
Hi @14stutzmanav -

Thanks for the prompt on this. I have now created a CITATION.cff file that decribes how to cite the most recent release of this repository: https://github.com/bergmanlab/drosophila-transposons/blob/master/CITATION.cff

If you look on the repository landing page, you can now see a "cite this repository" button, which if clicked will generate a citation in APA or Bibtex format, e.g.

Ashburner, M., Bayraktaroglu, L., Benos, T., Chillemi, J., Crosby, L., de Grey, A., Han, S., Kaminker, J., Lewis, S., Liao, G., Reese, M., & Bergman, C. (2021). Drosophila transposon canonical sequences (Version 10.2) [Data set]. https://github.com/bergmanlab/drosophila-transposons/

```
@misc{Ashburner_Drosophila_transposon_canonical_2021,
author = {Ashburner, Michael and Bayraktaroglu, Leyla and Benos, Takis and Chillemi, Joe and Crosby, Lynn and de Grey, Aubrey and Han, Shunhua and Kaminker, Josh and Lewis, Suzi and Liao, Guochun and Reese, Martin and Bergman, Casey},
month = {8},
title = {{Drosophila transposon canonical sequences}},
url = {https://github.com/bergmanlab/drosophila-transposons/},
year = {2021}
}
```
Please let me know if this is sufficient for your purposes.

Thanks,
Casey
